### ISSUE TITLE
Allow Vayder to accept Joi options

### ISSUE THREAD

**Issue by stevendaniels** [naveedn/vayder#1]
Currently, there is no way to pass in options for a validation.
Something like:

```
app.post('/blah',
  vayder.validateBody(blahSchema, {abortEarly: false}),
  (req, res) => { res.send('Hello World!');}
);
```

See: 
+ https://github.com/continuationlabs/celebrate#api
+ https://github.com/hapijs/joi/blob/master/API.md#validatevalue-schema-options-callback

**Comment by naveedn** [comment]
Understood. This is fair, I will implement this. Thanks for raising the feature request!

**Comment by naveedn** [comment]
Code added, closing issue.
